apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: backstage-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: cluster/backstage
        property: db_password
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: cluster/backstage
        property: github_token
    - secretKey: ARGOCD_ADMIN_PASSWORD
      remoteRef:
        key: cluster/backstage
        property: argocd_admin_password
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: cluster/backstage
        property: github_client_id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: cluster/backstage
        property: github_client_secret
    - secretKey: GRAFANA_TOKEN
      remoteRef:
        key: cluster/backstage
        property: grafana_token
