apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  project: system

  source:
    repoURL: https://github.com/keycloak/keycloak-k8s-resources
    targetRevision: 26.5.7
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
