apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-self.yaml
  - argocd-config.yaml
  - external-secrets.yaml
  - external-secrets-config.yaml
  - security-trivy-operator.yaml
  - security-kyverno.yaml
  - security-kyverno-policies.yaml
  - security-policy-reporter.yaml
  - keycloak-operator.yaml
  - traefik-config.yaml
