apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: system

  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno-policies
    targetRevision: 3.8.0
    helm:
      values: |
        validationFailureAction: Audit
        podSecurityStandard: restricted
        validationAllowExistingViolations: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
