apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-scm-token
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: github-scm-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cluster/backstage
        property: github_token
