apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - servicemonitors.yaml
  - externalsecret-github-scm.yaml
  - serviceaccount-backstage-token-sync.yaml
  - job-backstage-account-token.yaml
