apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-catalog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: apps
  source:
    repoURL: https://github.com/TourinhoM/app-catalog.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: app-catalog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
