apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-reviews
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: apps
  source:
    repoURL: https://github.com/TourinhoM/app-reviews.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: app-reviews
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 15
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
