apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Stack de observabilidade (Prometheus, Grafana, Alertmanager, Loki, OTel Collector) e dashboards
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://open-telemetry.github.io/opentelemetry-helm-charts   # otel-gateway + otel-agent
    - https://github.com/TourinhoM/platform-observe
    - https://github.com/TourinhoM/platform-gitops
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
