apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Serviços de plataforma (auth, data, backstage)
  sourceRepos:
    - https://github.com/TourinhoM/platform-auth        # era deploy-keycloak
    - https://github.com/TourinhoM/platform-data        # era deploy-postgresql
    - https://github.com/TourinhoM/platform-backstage
    - https://backstage.github.io/charts
    - https://github.com/keycloak/keycloak-k8s-resources
    - https://stakater.github.io/stakater-charts          # reloader
  destinations:
    - namespace: keycloak
      server: https://kubernetes.default.svc
    - namespace: infra          # migrar → platform-data quando o repo for migrado
      server: https://kubernetes.default.svc
    - namespace: platform-data
      server: https://kubernetes.default.svc
    - namespace: backstage
      server: https://kubernetes.default.svc
    - namespace: reloader
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

