apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Serviços de plataforma (auth, data, backstage)
  sourceRepos:
    - https://github.com/TourinhoM/platform-auth
    - https://github.com/TourinhoM/platform-data
    - https://github.com/TourinhoM/platform-backstage
    - https://backstage.github.io/charts
    - https://github.com/keycloak/keycloak-k8s-resources
  destinations:
    - namespace: keycloak
      server: https://kubernetes.default.svc
    - namespace: infra
      server: https://kubernetes.default.svc
    - namespace: platform-data
      server: https://kubernetes.default.svc
    - namespace: backstage
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

