apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  description: Substrato do cluster — Argo CD self-management, External Secrets, Keycloak Operator, cert-manager, Kyverno, policy-reporter, Trivy Operator, Traefik config
  # sourceRepos/destinations escopados aos apps de system.
  sourceRepos:
    - https://github.com/TourinhoM/platform-gitops       # argocd self/config, external-secrets-config
    - https://github.com/TourinhoM/platform-network      # cert-manager-config
    - https://charts.external-secrets.io                 # External Secrets Operator
    - https://charts.jetstack.io                         # cert-manager
    - https://aquasecurity.github.io/helm-charts/        # Trivy Operator
    - https://kyverno.github.io/kyverno/                 # Kyverno + policies
    - https://kyverno.github.io/policy-reporter/         # policy-reporter
    - https://github.com/keycloak/keycloak-k8s-resources # Keycloak Operator
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: keycloak
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: trivy-system
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: policy-reporter
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  # Whitelist cluster-wide para os CRDs/ClusterRoles/webhooks dos operators.
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
