apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-postgresql-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform
  source:
    repoURL: https://github.com/TourinhoM/platform-data.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 15
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

# TODO: criar Application de prod e usar segredos seguros.

