apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra

# TODO (Keycloak):
# - Preferir Helm chart oficial/Bitnami e versionar values
# - Configurar Ingress, TLS e hostname
# - Configurar Postgres externo (se aplicável)
# - Segredos via External Secrets/SOPS/SealedSecrets

resources: []

