apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Plano:
# - Definir namespaces do ambiente
# - Incluir “infra” (Postgres/Keycloak/Ingress/etc)
# - Aplicar patches e labels comuns via `lib/kustomize/*`

resources:
  - namespaces/infra.yaml
  - infra/postgresql
  - infra/keycloak

