apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO: definir namespaces, infra e patches/labels comuns.

resources:
  - namespaces/infra.yaml
  - infra/postgresql
  - infra/keycloak

