apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: system
  source:
    repoURL: https://github.com/TourinhoM/platform-gitops
    targetRevision: main
    path: backstage
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 15
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
