apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/system.yaml
  - projects/monitoring.yaml
  - projects/platform.yaml
  - projects/apps.yaml
  - projects/scaffolded-apps.yaml
  - projects/security.yaml
  - projects/backstage.yaml
  - projects/crossplane.yaml
  - projects/platform-apis.yaml
  - projects/app-of-apps.yaml
  - security-cert-manager-app.yaml
  - security-cert-manager-config-app.yaml
  - system-app.yaml
  - monitoring-app.yaml
  - platform-app.yaml
  - security-app.yaml
  - crossplane-app.yaml
  - platform-apis-app.yaml
  - apps-app.yaml
  - infra-keycloak.yaml
  - backstage-app.yaml
