apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects/system.yaml
  - projects/monitoring.yaml
  - projects/platform.yaml
  - projects/apps.yaml
  - system-app.yaml
  - monitoring-app.yaml
  - platform-app.yaml
  - apps-app.yaml
