apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: app-of-apps
  source:
    repoURL: https://github.com/TourinhoM/platform-gitops
    targetRevision: main
    path: apps/system
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
